language: python
env:
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
install:
    - pip install tox nose coverage python-coveralls
script:
    - tox
after_success:
  - coveralls
